# Use root/example as user/password credentials
version: "3.7"
services:
  mysql-server:
    image: mysql:8.0.19
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: globe
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
#    volumes:
#      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis-server:
    image: redis:6.2.3
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"

  mongo-server:
    image: mongo
    container_name: "mongo"
    restart: always
    command: --serviceExecutor adaptive
#    ports:
#      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: "mongo-express"
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: "zookeeper"
    restart: always
    ports:
      - "2181:2181"

  kafka-server:
    image: "wurstmeister/kafka"
    container_name: "kafka"
    restart: always
    ports:
      - "9092:9092"
#    hostname: kafka
#    links:
#      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
