# Use root/example as user/password credentials
version: "3.7"
services:
  mysql-server:
    image: mysql:8.0.19
    container_name: "mysql"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: globe
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
#    volumes:
#      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis-server:
    image: redis:6.2.3
    container_name: "redis"
    restart: always
    ports:
      - "6379:6379"

  mongo-server:
    image: mongo
    container_name: "mongo"
    restart: always
    command: --serviceExecutor adaptive
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example

  kafka-server:
    image: kafkamanager/kafka-manager:3.0.0.4
    container_name: "kafka"
    restart: always
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1